[build.environment]
NODE_VERSION = "20"
AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[functions]
directory = "functions"
external_node_modules = ["@sparticuz/chromium"] # https://github.com/Sparticuz/chromium/issues/24#issuecomment-1414107620

[[redirects]]
from = "/*"
to = "/.netlify/functions/screenshot"
status = 200
force = true